### PR TITLE
Update our fork from upstream

### PR DESCRIPTION
**Pull request by stephengtuggy**

### CODE REVIEW

**Comment by BenjamenMeyer** [comment]
FYI - this is going to be big enough that's its going to be hard to review. So probably just going to approve when the time comes.

**Comment by stephengtuggy** [comment]
> FYI - this is going to be big enough that's its going to be hard to review. So probably just going to approve when the time comes.

@BenjamenMeyer understood. There's really only a few lines of changes that I make on top of each new delta from upstream. And we may not need to keep maintaining this repository anyway; in my latest branch, I've found a way to avoid using this repo altogether.

Will keep you updated.

**Comment by BenjamenMeyer** [comment]
Might be wise to setup a GitHub action to do rebases and submit PRs, dependabot style

**Comment by stephengtuggy** [comment]
@BenjamenMeyer can we close this PR, and archive our fork of the repo? We don't need it with the latest 0.9.x code.

Also, can you maybe cut a new 0.9 alpha or beta release, if you haven't already? I'm a bit concerned that alpha 4 may be pulling the outdated code from our fork of this repo. Which wouldn't be good, because that might pull in the compromised `xz` library and so forth.

Thanks!

**Pull request closed without merging**
